### ISSUE TITLE
running `npm run build` fails with an error, running `aegir-build` directly works fine.

### ISSUE THREAD

**Issue by dryajov** [dignifiedquire/pull-length-prefixed#11]
I get this error when I run `npm run build` on the package:

```

> pull-length-prefixed@1.2.0 build /Users/dryajov/personal/projects/ipfs/pull-length-prefixed
> aegir-build

[10:37:43] Starting 'clean:browser'...
[10:37:43] Starting 'clean:node'...
[10:37:43] Finished 'clean:browser' after 5.25 ms
[10:37:43] Starting 'build:browser'...
[10:37:43] 'build:browser' errored after 51 ms
[10:37:43] WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'debug'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   The 'debug' property was removed in webpack 2.
   Loaders should be updated to allow passing this option via loader options in module.rules.
   Until loaders are updated one can use the LoaderOptionsPlugin to switch loaders into debug mode:
   plugins: [
     new webpack.LoaderOptionsPlugin({
       debug: true
     })
   ]
 - configuration.module has an unknown property 'postLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence? }
   Options affecting the normal modules (`NormalModuleFactory`).
    at webpack (/Users/dryajov/personal/projects/ipfs/pull-length-prefixed/node_modules/webpack/lib/webpack.js:19:9)
    at Object.fn (/Users/dryajov/personal/projects/ipfs/pull-length-prefixed/node_modules/aegir/tasks/build/browser.js:35:5)
    at Gulp.taskFunction (/Users/dryajov/personal/projects/ipfs/pull-length-prefixed/node_modules/gulp-require-tasks/index.js:65:26)
    at module.exports (/Users/dryajov/personal/projects/ipfs/pull-length-prefixed/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/dryajov/personal/projects/ipfs/pull-length-prefixed/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/dryajov/personal/projects/ipfs/pull-length-prefixed/node_modules/orchestrator/index.js:214:10)
    at /Users/dryajov/personal/projects/ipfs/pull-length-prefixed/node_modules/orchestrator/index.js:279:18
    at finish (/Users/dryajov/personal/projects/ipfs/pull-length-prefixed/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/dryajov/personal/projects/ipfs/pull-length-prefixed/node_modules/orchestrator/lib/runTask.js:29:3)
    at next (/Users/dryajov/personal/projects/ipfs/pull-length-prefixed/node_modules/rimraf/rimraf.js:74:7)
    at CB (/Users/dryajov/personal/projects/ipfs/pull-length-prefixed/node_modules/rimraf/rimraf.js:110:9)
    at /Users/dryajov/personal/projects/ipfs/pull-length-prefixed/node_modules/rimraf/rimraf.js:136:14
    at FSReqWrap.oncomplete (fs.js:123:15)
[10:37:43] Finished 'clean:node' after 55 ms

```

**Comment by dignifiedquire** [comment]
Fixed on `master`
